- 1.1.10rc3
- _NAME: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, pointer_speed, dpi, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4097
  _modelId: B354407CC33E
  _sensitive: {change-host: false, divert-gkeys: true, divert-keys: ignore, m-key-leds: false, mr-key-led: ignore, onboard_profiles: true, report_rate: ignore}
  _serial: A502B0E1
  _unitId: A502B0E1
  _wpid: 407C
  change-host: null
  divert-gkeys: true
  divert-keys: {209: 0, 210: 0}
  m-key-leds: {1: true, 2: false, 4: false}
  mr-key-led: true
  onboard_profiles: 1
  report_rate: '1'
- _NAME: G502 Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, pointer_speed, speed-change, backlight,
    backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys,
    m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4097
  _modelId: 407FC08D0000
  _sensitive: {dpi: false, hires-scroll-mode: true, hires-smooth-invert: false, hires-smooth-resolution: true, onboard_profiles: ignore, report_rate: ignore}
  _serial: DDDAADBC
  _unitId: DDDAADBC
  _wpid: 407F
  dpi: '800'
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  onboard_profiles: 1
  report_rate: '1'
- _NAME: G502 Lightspeed Gaming Mouse
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
- _NAME: Wireless Presenter R400
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 7AF46EE8
  _unitId: '00000000'
  _wpid: '4033'
- _NAME: Wireless Presenter R400
  _modelId: Wireless Presenter R400
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 7AF46EE8
  _unitId: '00000000'
  _wpid: '4033'
